elevator:
  # The cooldown in ticks
  cooldown: 60
  # How tall elevators can be
  # Individual elevators can be adjusted to be taller
  # with /elevator setmaxheight <max-height>
  max-height: 96
  # The rope block.
  # Most blocks should work, but it is recommended that you
  # use something that doesn't need to be supported by other blocks.
  # Specify block states with vanilla syntax.
  rope-block: chain

  # The floor scanner.
  scanner:
    # Allow elevators without floor scanner blocks to use the top and bottom of the elevator shaft as floors
    allow-no-scanner: true
    # The block type to scan from
    scanner-block: observer
    # If directional
    scanner-directional: true
    # The block type to look for
    floor-block: lodestone