elevator:
  # The cooldown in ticks
  cooldown: 60
  # How tall elevators can be
  max-height: 96
  # The rope block.
  # Most blocks should work, but it is recommended that you
  # use something that doesn't need to be supported by other blocks.
  # Specify block states with vanilla syntax.
  rope-block: chain

  # The floor scanner.
  scanner:
    # The block type to scan from
    scanner-block: observer
    # If directional
    scanner-directional: true
    # The block type to look for
    floor-block: lodestone