messages:
  error-not-in-elevator: '&4You are not in an elevator!'

  no-floors: '&cNo floors found. Use &e/elevator scan&c to scan for floors.'
  current-floor: '&cCrouch: {down}&8 | &aCurrent: {current}&8 | &bJump: {up}'
  floor: '&c▼ {down}&8 | &aSelected: {current}&7 (jump or crouch to go)&8 | &b▲ {up}'
  # Used e.g. when the elevator cannot go lower
  no-floor: '&7&m   &r'
  # For British floor names:
  #  default-ground-floor-name: 'G/F'
  #  default-floor-name: '{floorMinusOne}/F'
  default-ground-floor-name: '1/F'
  default-floor-name: '{floor}/F'

  enter-floor-name: '&aEnter new floor name\n&9Current floor name: &e{floorName}&7 (Enter to cancel editing)'

  begin-maintenance: '&cThe elevator is now in maintenance.'
  end-maintenance: '&cThe elevator is no longer in maintenance.'

  edit-cabin:
    instructions: '&3Right click with a &aSlime Ball&3 to edit the cabin position.'
    pos1: '&2Right click the &efirst position&2 with a &aSlime Ball&2.'
    pos2: '&2Right click the &esecond position&2 with a &aSlime Ball&3'
    success: '&aThe cabin position has been updated.'
    failed: '&cThe cabin position was not updated.'

  cooldown: '&cStopping for {cooldown} seconds'
  maintenance: '&cThis elevator is in maintenance.'

  scan:
    result: '&eFound {floors} floors:'
    scanned-floor: '- {name} @ Y={y}'
    scanned-current-floor: '> {name} @ Y={y}'

elevator:
  # The cooldown in ticks
  cooldown: 60
  # How tall elevators can be
  max-height: 96

  # The floor scanner.
  scanner:
    # The block type to scan from
    scanner-block: observer
    # If directional
    scanner-directional: true
    # The block type to look for
    floor-block: lodestone